spring:
  jpa:
    primary:
      show-sql: false  # 是否打印sql语句
      generate-ddl: true
    hibernate:
      ddl-auto: none # 数据库的操作模式
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # 是否在控制台打印SQL语句
  redis:
    database: 2 # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    host: 127.0.0.1 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  data:
    mongodb:
      second:
        enabled: true # 是否开启第二数据源
        host: 127.0.0.1
        port: 18009
        authentication-database: admin # 需要上授权的数据库，不然连接不上
        database: dist
        username: user
        password: pass
  aop:
    auto: true
    proxy-target-class: true # 默认设置为false,使用的是标准Java动态代理的实现（接口），而不是cglib（类）
  datasource:
    sql-script-encoding: utf-8 # 解决中文乱码
    first:
      username: user
      password: pass
      url: jdbc:oracle:thin:@127.0.0.1/ORCL   # jdbc:postgresql://127.0.0.1:2121/postgres
      driver-class-name: oracle.jdbc.driver.OracleDriver  # org.postgresql.Driver
      maxActive: 200
      initialSize: 10
      minIdle: 10
      maxWait: 60000
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: false
      minEvictableIdleTimeMillis: 60000
      timeBetweenEvictionRunsMillis: 60000
      testOnBorrow: false
      validationQuery: select 1 from dual # oracle数据库
      #validationQuery: select version()  # pg数据库
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 200
      monitor: false # 是否启用数据库连接池监控，开启后损失部分性能
  boot:
    admin:
      url: http://127.0.0.1:8080/dgp-admin-server #springboot监控访问地址。
      client:
        name: dgp-ars-server-service
        service-base-url: http://127.0.0.1:8080 #当前服务访问IP端口
        enabled: true #客户端开关

# springboot 保证调用 /bus/refresh的时候不需要验证
management:
  security:
    enabled: false #springboot-admin，关闭安全性

# 项目模块日志文件
logging:
  config: classpath:logback-spring.xml  # 日志配置文件
  app: dgp-ars-server-service  # 日志文件名称
  level: info  # 日志级别

# dubbo 配置
dubbo:
  application:
    name: arsprovider
  registry:
    address: zookeeper://127.0.0.1:2181
    file: N/A  # 直连方式，仅限测试阶段使用
  protocol:
    port: 40001
  annotation:
    package: 'com.dist.ars.service,com.dist.ars.manager.remote'
  provider: # 提供者服务版本
    version: 1.0.0
  consumer: # 消费者服务版本
    version: 1.0.0

# feign配置：请求路径
feign:
  dme:
    task: http://127.0.0.1:8082    # 模型系统任务相关
    result: http://127.0.0.1:8083  # 模型系统拉取结果相关